defaults:
  - arch: trm
  - _self_

hydra:
  output_subdir: null

data_paths: ['data/factorization-test']
data_paths_test: []

evaluators: []

global_batch_size: 768

epochs: 50000
eval_interval: 5000
checkpoint_every_eval: true

lr: 1e-4
lr_min_ratio: 0.1
lr_warmup_steps: 1000
lr_num_cycles: 3.0
lr_scheduler:
  name: reduce_on_plateau
  metric: train/lm_loss
  mode: min
  factor: 0.5
  patience: 4
  threshold: 1e-3
  cooldown: 2
  min_lr: 1e-6

beta1: 0.9
beta2: 0.95
weight_decay: 1.0
puzzle_emb_weight_decay: 1.0

puzzle_emb_lr: 1e-4

seed: 0
min_eval_interval: 0

ema: true
ema_rate: 0.999
freeze_weights: false

run_name: primes-init

